# -*- coding: utf-8 -*-
"""Phonepe Stremlit Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RisJce_hV169Mbalg_KvZH7GH8NgF4MM
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# -----------------------------
# Page config
# -----------------------------
st.set_page_config(
    page_title="PhonePe Transaction Insights Dashboard",
    page_icon="📊",
    layout="wide"
)

st.title("📊 PhonePe Transaction Insights Dashboard")
st.markdown("Interactive dashboard for transaction, user engagement, and insurance insights.")

sns.set_style("whitegrid")

# -----------------------------
# Helpers
# -----------------------------
def safe_read_csv(path: str) -> pd.DataFrame:
    if os.path.exists(path):
        return pd.read_csv(path)
    return pd.DataFrame()

@st.cache_data
def load_data() -> dict:
    files = {
        "agg_trans": "aggregated_transaction.csv",
        "agg_user": "aggregated_user.csv",
        "agg_ins": "aggregated_insurance.csv",
        "map_trans": "map_transaction.csv",
        "map_user": "map_user.csv",
        "map_ins": "map_insurance.csv",
        "top_trans": "top_transaction.csv",
        "top_user": "top_user.csv",
        "top_ins": "top_insurance.csv",
    }
    return {name: safe_read_csv(path) for name, path in files.items()}


def require_columns(df: pd.DataFrame, cols: list[str]) -> bool:
    return not df.empty and all(col in df.columns for col in cols)


def draw_bar(df: pd.DataFrame, x: str, y: str, title: str, rotate: int = 45):
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(data=df, x=x, y=y, ax=ax)
    ax.set_title(title)
    ax.tick_params(axis="x", rotation=rotate)
    st.pyplot(fig)


def draw_line(df: pd.DataFrame, x: str, y: str, title: str, rotate: int = 0):
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.lineplot(data=df, x=x, y=y, marker="o", ax=ax)
    ax.set_title(title)
    ax.tick_params(axis="x", rotation=rotate)
    st.pyplot(fig)


def draw_scatter(df: pd.DataFrame, x: str, y: str, title: str):
    fig, ax = plt.subplots(figsize=(8, 5))
    sns.scatterplot(data=df, x=x, y=y, ax=ax)
    ax.set_title(title)
    st.pyplot(fig)


def draw_pie(series: pd.Series, title: str):
    fig, ax = plt.subplots(figsize=(7, 7))
    ax.pie(series.values, labels=series.index, autopct="%1.1f%%", startangle=90)
    ax.set_title(title)
    st.pyplot(fig)


def draw_heatmap(df: pd.DataFrame, title: str):
    fig, ax = plt.subplots(figsize=(8, 5))
    sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm", ax=ax)
    ax.set_title(title)
    st.pyplot(fig)


# -----------------------------
# Load
# -----------------------------
data = load_data()
agg_trans = data["agg_trans"]
agg_user = data["agg_user"]
agg_ins = data["agg_ins"]
map_trans = data["map_trans"]
map_user = data["map_user"]
map_ins = data["map_ins"]
top_trans = data["top_trans"]
top_user = data["top_user"]
top_ins = data["top_ins"]

st.sidebar.header("Dashboard Controls")
section = st.sidebar.radio(
    "Select Section",
    [
        "Overview",
        "Transactions",
        "Users & Devices",
        "Insurance",
        "Geography",
        "Correlation & Insights",
        "Raw Data"
    ]
)

# Optional filters
if not agg_trans.empty and "Year" in agg_trans.columns:
    agg_trans["Year"] = agg_trans["Year"].astype(str)
    years = sorted(agg_trans["Year"].dropna().unique().tolist())
    selected_years = st.sidebar.multiselect("Filter Year", years, default=years)
    if selected_years:
        agg_trans = agg_trans[agg_trans["Year"].isin(selected_years)]
        if not agg_ins.empty and "Year" in agg_ins.columns:
            agg_ins["Year"] = agg_ins["Year"].astype(str)
            agg_ins = agg_ins[agg_ins["Year"].isin(selected_years)]
        if not agg_user.empty and "Year" in agg_user.columns:
            agg_user["Year"] = agg_user["Year"].astype(str)
            agg_user = agg_user[agg_user["Year"].isin(selected_years)]
        if not map_trans.empty and "Year" in map_trans.columns:
            map_trans["Year"] = map_trans["Year"].astype(str)
            map_trans = map_trans[map_trans["Year"].isin(selected_years)]
        if not map_user.empty and "Year" in map_user.columns:
            map_user["Year"] = map_user["Year"].astype(str)
            map_user = map_user[map_user["Year"].isin(selected_years)]
        if not map_ins.empty and "Year" in map_ins.columns:
            map_ins["Year"] = map_ins["Year"].astype(str)
            map_ins = map_ins[map_ins["Year"].isin(selected_years)]
        if not top_trans.empty and "Year" in top_trans.columns:
            top_trans["Year"] = top_trans["Year"].astype(str)
            top_trans = top_trans[top_trans["Year"].isin(selected_years)]
        if not top_user.empty and "Year" in top_user.columns:
            top_user["Year"] = top_user["Year"].astype(str)
            top_user = top_user[top_user["Year"].isin(selected_years)]
        if not top_ins.empty and "Year" in top_ins.columns:
            top_ins["Year"] = top_ins["Year"].astype(str)
            top_ins = top_ins[top_ins["Year"].isin(selected_years)]

# -----------------------------
# Overview
# -----------------------------
if section == "Overview":
    st.subheader("Overview")

    c1, c2, c3 = st.columns(3)

    total_amount = agg_trans["Transaction_amount"].sum() if "Transaction_amount" in agg_trans.columns else 0
    total_count = agg_trans["Transaction_count"].sum() if "Transaction_count" in agg_trans.columns else 0
    total_users = agg_user["RegisteredUsers"].sum() if "RegisteredUsers" in agg_user.columns else 0

    c1.metric("Total Transaction Amount", f"₹ {total_amount:,.0f}")
    c2.metric("Total Transaction Count", f"{int(total_count):,}")
    c3.metric("Total Registered Users", f"{int(total_users):,}")

    if require_columns(agg_trans, ["Year", "Transaction_amount"]):
        yearly_amt = agg_trans.groupby("Year", as_index=False)["Transaction_amount"].sum()
        draw_line(yearly_amt, "Year", "Transaction_amount", "Year-wise Transaction Amount")

    if require_columns(agg_trans, ["Transaction_type", "Transaction_amount"]):
        type_amt = agg_trans.groupby("Transaction_type", as_index=False)["Transaction_amount"].sum().sort_values(
            "Transaction_amount", ascending=False
        )
        draw_bar(type_amt, "Transaction_type", "Transaction_amount", "Transaction Amount by Category")

# -----------------------------
# Transactions
# -----------------------------
elif section == "Transactions":
    st.subheader("Transaction Analysis")

    if require_columns(agg_trans, ["Year", "Transaction_amount"]):
        yearly_amt = agg_trans.groupby("Year", as_index=False)["Transaction_amount"].sum()
        draw_line(yearly_amt, "Year", "Transaction_amount", "Chart 1: Transaction Amount by Year")

    if require_columns(agg_trans, ["Year", "Transaction_count"]):
        yearly_cnt = agg_trans.groupby("Year", as_index=False)["Transaction_count"].sum()
        draw_line(yearly_cnt, "Year", "Transaction_count", "Chart 2: Transaction Count by Year")

    if require_columns(agg_trans, ["Transaction_type", "Transaction_amount"]):
        cat_amt = agg_trans.groupby("Transaction_type", as_index=False)["Transaction_amount"].sum().sort_values(
            "Transaction_amount", ascending=False
        )
        draw_bar(cat_amt, "Transaction_type", "Transaction_amount", "Chart 3: Transaction Amount by Category")

    if require_columns(agg_trans, ["Transaction_type", "Transaction_count"]):
        cat_cnt = agg_trans.groupby("Transaction_type", as_index=False)["Transaction_count"].sum().sort_values(
            "Transaction_count", ascending=False
        )
        draw_bar(cat_cnt, "Transaction_type", "Transaction_count", "Chart 4: Transaction Count by Category")

    if require_columns(agg_trans, ["Quarter", "Transaction_amount"]):
        q_amt = agg_trans.groupby("Quarter", as_index=False)["Transaction_amount"].sum()
        draw_bar(q_amt, "Quarter", "Transaction_amount", "Chart 5: Quarter-wise Transaction Amount", rotate=0)

    if require_columns(agg_trans, ["Quarter", "Transaction_count"]):
        q_cnt = agg_trans.groupby("Quarter", as_index=False)["Transaction_count"].sum()
        draw_bar(q_cnt, "Quarter", "Transaction_count", "Chart 6: Quarter-wise Transaction Count", rotate=0)

# -----------------------------
# Users & Devices
# -----------------------------
elif section == "Users & Devices":
    st.subheader("User Engagement & Device Analysis")

    if require_columns(agg_user, ["Brand", "User_count"]):
        brand_users = agg_user.groupby("Brand", as_index=False)["User_count"].sum().sort_values(
            "User_count", ascending=False
        ).head(10)
        draw_bar(brand_users, "Brand", "User_count", "Chart 13: Device Brand-wise User Count")

        draw_pie(brand_users.set_index("Brand")["User_count"], "Chart 14: Device Brand Share")

    if require_columns(map_user, ["State", "RegisteredUsers"]):
        state_users = map_user.groupby("State", as_index=False)["RegisteredUsers"].sum().sort_values(
            "RegisteredUsers", ascending=False
        ).head(10)
        draw_bar(state_users, "State", "RegisteredUsers", "Chart 10: Top States by Registered Users")

    if require_columns(map_user, ["State", "AppOpens"]):
        state_opens = map_user.groupby("State", as_index=False)["AppOpens"].sum().sort_values(
            "AppOpens", ascending=False
        ).head(10)
        draw_bar(state_opens, "State", "AppOpens", "Chart 11: Top States by App Opens")

    if require_columns(map_user, ["RegisteredUsers", "AppOpens"]):
        draw_scatter(map_user, "RegisteredUsers", "AppOpens", "Chart 12: Registered Users vs App Opens")

# -----------------------------
# Insurance
# -----------------------------
elif section == "Insurance":
    st.subheader("Insurance Analysis")

    if require_columns(agg_ins, ["Year", "Insurance_amount"]):
        ins_amt = agg_ins.groupby("Year", as_index=False)["Insurance_amount"].sum()
        draw_line(ins_amt, "Year", "Insurance_amount", "Chart 15: Insurance Amount by Year")

    if require_columns(agg_ins, ["Year", "Insurance_count"]):
        ins_cnt = agg_ins.groupby("Year", as_index=False)["Insurance_count"].sum()
        draw_line(ins_cnt, "Year", "Insurance_count", "Chart 16: Insurance Count by Year")

    if require_columns(map_ins, ["State", "Insurance_amount"]):
        top_states_ins_amt = map_ins.groupby("State", as_index=False)["Insurance_amount"].sum().sort_values(
            "Insurance_amount", ascending=False
        ).head(10)
        draw_bar(top_states_ins_amt, "State", "Insurance_amount", "Chart 17: Top States by Insurance Amount")

# -----------------------------
# Geography
# -----------------------------
elif section == "Geography":
    st.subheader("Geographical Performance")

    if require_columns(map_trans, ["State", "Transaction_amount"]):
        top_states_amt = map_trans.groupby("State", as_index=False)["Transaction_amount"].sum().sort_values(
            "Transaction_amount", ascending=False
        ).head(10)
        draw_bar(top_states_amt, "State", "Transaction_amount", "Chart 7: Top 10 States by Transaction Amount")

        bottom_states_amt = map_trans.groupby("State", as_index=False)["Transaction_amount"].sum().sort_values(
            "Transaction_amount", ascending=True
        ).head(10)
        draw_bar(bottom_states_amt, "State", "Transaction_amount", "Chart 9: Bottom 10 States by Transaction Amount")

    if require_columns(map_trans, ["State", "Transaction_count"]):
        top_states_cnt = map_trans.groupby("State", as_index=False)["Transaction_count"].sum().sort_values(
            "Transaction_count", ascending=False
        ).head(10)
        draw_bar(top_states_cnt, "State", "Transaction_count", "Chart 8: Top 10 States by Transaction Count")

    if require_columns(top_trans, ["District", "Transaction_amount"]):
        top_district_amt = top_trans.groupby("District", as_index=False)["Transaction_amount"].sum().sort_values(
            "Transaction_amount", ascending=False
        ).head(10)
        draw_bar(top_district_amt, "District", "Transaction_amount", "Chart 18: Top Districts by Transaction Amount", rotate=75)

    if require_columns(top_trans, ["District", "Transaction_count"]):
        top_district_cnt = top_trans.groupby("District", as_index=False)["Transaction_count"].sum().sort_values(
            "Transaction_count", ascending=False
        ).head(10)
        draw_bar(top_district_cnt, "District", "Transaction_count", "Chart 19: Top Districts by Transaction Count", rotate=75)

    if require_columns(top_trans, ["Pincode", "Transaction_amount"]):
        top_pin_amt = top_trans.groupby("Pincode", as_index=False)["Transaction_amount"].sum().sort_values(
            "Transaction_amount", ascending=False
        ).head(10)
        top_pin_amt["Pincode"] = top_pin_amt["Pincode"].astype(str)
        draw_bar(top_pin_amt, "Pincode", "Transaction_amount", "Chart 20: Top Pincodes by Transaction Amount", rotate=45)

    if require_columns(top_trans, ["Pincode", "Transaction_count"]):
        top_pin_cnt = top_trans.groupby("Pincode", as_index=False)["Transaction_count"].sum().sort_values(
            "Transaction_count", ascending=False
        ).head(10)
        top_pin_cnt["Pincode"] = top_pin_cnt["Pincode"].astype(str)
        draw_bar(top_pin_cnt, "Pincode", "Transaction_count", "Chart 21: Top Pincodes by Transaction Count", rotate=45)

# -----------------------------
# Correlation & Insights
# -----------------------------
elif section == "Correlation & Insights":
    st.subheader("Correlation & Key Insights")

    numeric_frames = []
    for df in [agg_trans, agg_user, agg_ins, map_trans, map_user, map_ins, top_trans, top_user, top_ins]:
        if not df.empty:
            numeric_frames.append(df.select_dtypes(include=np.number))

    merged_numeric = pd.concat(numeric_frames, axis=1) if numeric_frames else pd.DataFrame()
    merged_numeric = merged_numeric.loc[:, ~merged_numeric.columns.duplicated()]

    if not merged_numeric.empty:
        draw_heatmap(merged_numeric, "Correlation Heatmap")

    st.markdown(
        """
        ### Key Business Insights
        - Digital transaction amount and count show strong growth over time.
        - A few states dominate transaction value and user engagement.
        - Device usage is concentrated around a few popular brands.
        - Insurance adoption is growing, but remains lower than core transaction activity.
        - District- and pincode-level analysis helps identify micro-markets for targeted campaigns.
        """
    )

# -----------------------------
# Raw Data
# -----------------------------
elif section == "Raw Data":
    st.subheader("Raw Data Explorer")
    dataset_name = st.selectbox(
        "Choose dataset",
        ["agg_trans", "agg_user", "agg_ins", "map_trans", "map_user", "map_ins", "top_trans", "top_user", "top_ins"]
    )
    selected_df = data[dataset_name]
    st.write(f"Shape: {selected_df.shape}")
    st.dataframe(selected_df)

st.sidebar.markdown("---")
st.sidebar.info(
    "Place the nine CSV files in the same folder as this app before running Streamlit."
)