# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVbbl9Vq1IAUnhKuBD-plE_D-WmZdKRr
"""

import os
import streamlit as st
import pandas as pd
import joblib
import numpy as np

st.set_page_config(page_title="Tourism Experience Analytics", layout="wide")

ARTIFACT_DIR = "artifacts"
DATA_FILE = "master_cleaned.csv"   # <-- keep this file in the same folder as app.py

# -------------------------
# Helpers
# -------------------------
def get_required_cols(pipe):
    """
    Get the exact feature columns used during training (from fitted pipeline).
    Works for sklearn Pipelines that were fit with pandas DataFrame.
    """
    if hasattr(pipe, "feature_names_in_"):
        return list(pipe.feature_names_in_)
    if hasattr(pipe, "named_steps") and "preprocess" in pipe.named_steps:
        pre = pipe.named_steps["preprocess"]
        if hasattr(pre, "feature_names_in_"):
            return list(pre.feature_names_in_)
    return None

@st.cache_resource
def load_models():
    reg_model = joblib.load(os.path.join(ARTIFACT_DIR, "rating_regression_model.joblib"))
    clf_model = joblib.load(os.path.join(ARTIFACT_DIR, "visitmode_classifier.joblib"))

    user_item = joblib.load(os.path.join(ARTIFACT_DIR, "user_item_matrix.joblib"))
    item_sim_collab = joblib.load(os.path.join(ARTIFACT_DIR, "item_similarity_collab.joblib"))
    content_sim = joblib.load(os.path.join(ARTIFACT_DIR, "item_similarity_content.joblib"))
    return reg_model, clf_model, user_item, item_sim_collab, content_sim

@st.cache_data
def load_data():
    if not os.path.exists(DATA_FILE):
        return None
    return pd.read_csv(DATA_FILE)

# -------------------------
# Check artifacts exist
# -------------------------
required_files = [
    "rating_regression_model.joblib",
    "visitmode_classifier.joblib",
    "user_item_matrix.joblib",
    "item_similarity_collab.joblib",
    "item_similarity_content.joblib",
]
missing = [f for f in required_files if not os.path.exists(os.path.join(ARTIFACT_DIR, f))]
if missing:
    st.error("Missing artifact files in ./artifacts:\n- " + "\n- ".join(missing))
    st.stop()

reg_model, clf_model, user_item, item_sim_collab, content_sim = load_models()
df = load_data()

st.title("Tourism Experience Analytics")
st.write("Regression (Rating) + Classification (VisitMode) + Recommendation (Hybrid)")

# -------------------------
# Load required columns from the models
# -------------------------
reg_cols = get_required_cols(reg_model)
clf_cols = get_required_cols(clf_model)

if reg_cols is None or clf_cols is None:
    st.error("Could not detect training feature columns from the saved models. Please retrain models using DataFrame input.")
    st.stop()

st.sidebar.header("Input Mode")

if df is None:
    st.warning(f"'{DATA_FILE}' not found. Put the same training dataset in this folder.")
    st.stop()

mode = st.sidebar.radio("Choose input method", ["Use an existing record (recommended)", "Manual (advanced)"])

# -------------------------
# Mode 1: Use existing record
# -------------------------
if mode == "Use an existing record (recommended)":
    st.subheader("Select a record from dataset")

    # Prefer TransactionId if present
    if "TransactionId" in df.columns:
        tx_ids = df["TransactionId"].dropna().unique().tolist()
        tx_id = st.selectbox("TransactionId", tx_ids[:5000])  # limit for UI
        row = df[df["TransactionId"] == tx_id].head(1)
    else:
        idx = st.number_input("Row index", min_value=0, max_value=len(df)-1, value=0, step=1)
        row = df.iloc[[int(idx)]]

    st.write("Selected row (preview):")
    st.dataframe(row.head(1))

    # Build X for each model using required columns
    X_reg = row.reindex(columns=reg_cols)
    X_clf = row.reindex(columns=clf_cols)

    # -------------------------
    # 1) Predict VisitMode
    # -------------------------
    st.subheader("1) Predict Visit Mode")
    if st.button("Predict VisitMode"):
        pred_mode = clf_model.predict(X_clf)[0]
        st.success(f"Predicted VisitMode: **{pred_mode}**")
        if "VisitMode" in row.columns:
            st.info(f"Actual VisitMode in data: **{row['VisitMode'].iloc[0]}**")

    # -------------------------
    # 2) Predict Rating
    # -------------------------
    st.subheader("2) Predict Rating")
    if st.button("Predict Rating"):
        pred_rating = float(reg_model.predict(X_reg)[0])
        st.success(f"Predicted Rating: **{pred_rating:.2f} / 5**")
        if "Rating" in row.columns:
            st.info(f"Actual Rating in data: **{row['Rating'].iloc[0]}**")

# -------------------------
# Mode 2: Manual input (advanced)
# -------------------------
else:
    st.subheader("Manual input (advanced)")
    st.caption("This creates inputs for ALL training columns. Use only if you need manual user input.")

    # Build a form for classification columns (often overlap with regression)
    all_cols = sorted(set(reg_cols).union(set(clf_cols)))

    inputs = {}
    with st.form("manual_form"):
        for col in all_cols:
            if col not in df.columns:
                # if column not in df, allow text input
                inputs[col] = st.text_input(col, value="")
                continue

            if pd.api.types.is_numeric_dtype(df[col]):
                default = float(df[col].dropna().median()) if df[col].notna().any() else 0.0
                inputs[col] = st.number_input(col, value=default)
            else:
                # limit options to avoid huge selectboxes
                options = df[col].dropna().astype(str).value_counts().head(200).index.tolist()
                inputs[col] = st.selectbox(col, options)

        submit = st.form_submit_button("Run Predictions")

    if submit:
        X = pd.DataFrame([inputs])

        # Ensure correct column order for each model
        X_reg = X.reindex(columns=reg_cols)
        X_clf = X.reindex(columns=clf_cols)

        pred_mode = clf_model.predict(X_clf)[0]
        pred_rating = float(reg_model.predict(X_reg)[0])

        st.success(f"Predicted VisitMode: **{pred_mode}**")
        st.success(f"Predicted Rating: **{pred_rating:.2f} / 5**")

# -------------------------
# 3) Recommendations
# -------------------------
st.subheader("3) Recommendations (Hybrid)")

user_id = st.number_input("UserId for Recommendations", min_value=1, value=int(df["UserId"].dropna().iloc[0]) if "UserId" in df.columns else 1, step=1)

def recommend_collab(user_id, top_n=10):
    if user_id not in user_item.index:
        return []
    user_ratings = user_item.loc[user_id]
    rated = user_ratings[user_ratings > 0].index.tolist()
    if not rated:
        return []
    scores = item_sim_collab[rated].dot(user_ratings[rated])
    scores = scores.drop(rated, errors="ignore").sort_values(ascending=False).head(top_n)
    return list(scores.index)

def recommend_hybrid(user_id, top_n=10, alpha=0.7):
    if user_id not in user_item.index:
        return recommend_collab(user_id, top_n=top_n)

    user_ratings = user_item.loc[user_id]
    rated = user_ratings[user_ratings > 0].index.tolist()
    if not rated:
        return []

    collab_scores = item_sim_collab[rated].dot(user_ratings[rated]).drop(rated, errors="ignore")
    collab_scores = collab_scores / (collab_scores.max() + 1e-9)

    liked = user_ratings[user_ratings >= user_ratings[user_ratings > 0].mean()].index.tolist()
    content_scores = pd.Series(0.0, index=collab_scores.index)

    for it in liked[:5]:
        if it in content_sim.index:
            sims = content_sim.loc[it].reindex(content_scores.index).fillna(0)
            content_scores += sims

    if content_scores.max() > 0:
        content_scores = content_scores / content_scores.max()

    final = alpha * collab_scores + (1 - alpha) * content_scores
    return list(final.sort_values(ascending=False).head(top_n).index)

if st.button("Recommend for User"):
    recs = recommend_hybrid(int(user_id), top_n=10)
    st.write("Recommended AttractionIds:", recs)