# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlzdexGmguO1fa8hXItxFkz9dRIFeAXt
"""

import streamlit as st
import numpy as np
import joblib

# ---- Compatibility for old/new Streamlit versions ----
try:
    cache_resource = st.cache_resource      # Streamlit ≥ 1.18
except AttributeError:
    cache_resource = st.cache              # Older Streamlit fallback

# ==============================
# 1. Load Saved Models
# ==============================

#@st.cache_resource
@cache_resource
def load_product_model():
    model = joblib.load("product_similarity_model.pkl")
    return model

#@st.cache_resource
@cache_resource
def load_rfm_model():
    model = joblib.load("rfm_kmeans_segment_model.pkl")
    return model


# ==============================
# 2. Helper Functions
# ==============================

def recommend_similar_products(product_name, product_model, top_n=5, min_similarity=0.0):
    product_similarity = product_model["product_similarity"]
    product_names = product_model["product_names"]
    product_index = product_model["product_index"]

    if not product_names:
        return None, []

    query = product_name.strip().lower()

    # exact match
    exact_matches = [p for p in product_names if p.lower() == query]

    if len(exact_matches) == 0:
        # substring fallback
        contains_matches = [p for p in product_names if query in p.lower()]
        if len(contains_matches) == 0:
            return None, []
        base_product = contains_matches[0]
    else:
        base_product = exact_matches[0]

    idx = product_index[base_product]
    sim_scores = list(enumerate(product_similarity[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    recommendations = []
    for i, score in sim_scores:
        if i == idx:
            continue
        if score < min_similarity:
            continue
        recommendations.append((product_names[i], score))
        if len(recommendations) >= top_n:
            break

    return base_product, recommendations


def predict_rfm_segment(recency, frequency, monetary, rfm_model):
    scaler = rfm_model["scaler"]
    kmeans = rfm_model["kmeans"]
    cluster_label_map = rfm_model.get("cluster_label_map", None)

    X = np.array([[recency, frequency, monetary]])
    X_scaled = scaler.transform(X)
    cluster_id = int(kmeans.predict(X_scaled)[0])

    if cluster_label_map is not None:
        label = cluster_label_map.get(cluster_id, f"Cluster {cluster_id}")
    else:
        label = f"Cluster {cluster_id}"

    return cluster_id, label


# ==============================
# 3. Streamlit App Layout
# ==============================

def main():
    st.set_page_config(
        page_title="🛒 Shopper Spectrum – Segmentation & Product Recs",
        layout="wide",
    )

    # ---------- load models once ----------
    with st.spinner("Loading models..."):
        product_model = load_product_model()
        rfm_model = load_rfm_model()

    # ---------- sidebar navigation ----------
    st.sidebar.title("Navigation")
    page = st.sidebar.radio(
        "Go to",
        ["Home", "Clustering", "Recommendation"],
        index=2  # default to Recommendation like the screenshot
    )

    # ========== HOME PAGE ==========
    if page == "Home":
        st.title("🛒 Shopper Spectrum")
        st.write(
            """
            Welcome to the demo app.

            - **Clustering** page: RFM-based customer segmentation
            - **Recommendation** page: Item-based collaborative product recommender
            """
        )

    # ========== CLUSTERING PAGE ==========
    elif page == "Clustering":
        st.title("Customer Segmentation")

        st.subheader("RFM-based Customer Segmentation")
        st.write(
            "Enter Recency, Frequency and Monetary values to predict the customer segment."
        )

        col1, col2, col3 = st.columns(3)

        with col1:
            recency = st.number_input(
                "Recency (days since last purchase)",
                min_value=0,
                max_value=3650,
                value=30,
                step=1,
            )

        with col2:
            frequency = st.number_input(
                "Frequency (number of purchases)",
                min_value=1,
                max_value=1000,
                value=5,
                step=1,
            )

        with col3:
            monetary = st.number_input(
                "Monetary (total spend)",
                min_value=1.0,
                value=500.0,
                step=10.0,
                format="%.2f",
            )

        if st.button("Predict Cluster"):
            cluster_id, label = predict_rfm_segment(
                recency, frequency, monetary, rfm_model
            )

            st.success(f"Predicted Segment: **{label}** (Cluster ID: {cluster_id})")

            st.markdown("#### Segment Interpretation")
            if "High" in label:
                st.write(
                    "- **High-value, loyal shopper.** Consider exclusive offers and loyalty rewards."
                )
            elif "Regular" in label:
                st.write(
                    "- **Regular customer.** Maintain engagement with personalised emails and cross-sell."
                )
            elif "Occasional" in label:
                st.write(
                    "- **Occasional buyer.** Use targeted discounts and reminders to increase activity."
                )
            elif "Risk" in label or "At-Risk" in label:
                st.write(
                    "- **At-risk customer.** Try re-engagement campaigns and special offers."
                )
            else:
                st.write("- Generic cluster. Use RFM values to design your own strategy.")

    # ========== RECOMMENDATION PAGE ==========
    elif page == "Recommendation":
        # centre layout similar to the mockup
        left, main, right = st.columns([1, 3, 1])

        with main:
            st.title("Product Recommender")

            st.write("Enter a product name to get **5 similar products**.")

            product_name_input = st.text_input(
                "Enter Product Name", value="", placeholder="e.g. GREEN VINTAGE SPOT BEAKER"
            )

            if st.button("Recommend"):
                if not product_name_input.strip():
                    st.warning("Please enter a product name.")
                else:
                    base_product, recs = recommend_similar_products(
                        product_name_input,
                        product_model,
                        top_n=5,
                        min_similarity=0.0,
                    )

                    if base_product is None or len(recs) == 0:
                        st.error("No similar products found. Try another product name.")
                    else:
                        st.markdown(
                            f"**Base Product Used:** {base_product}"
                        )

                        st.markdown("#### Recommended Products")
                        for i, (prod, score) in enumerate(recs, start=1):
                            st.markdown(f"{i}. **{prod}**")

if __name__ == "__main__":
    main()